### ISSUE TITLE
add the ability to exit clean even with failing tests

### ISSUE THREAD

**Issue by aaronlippold** [actionshub/test-kitchen#5] opened 2020-07-27 17:10 UTC
I have verifer tests that I would like to allow to fail and I and 'validating' my run with a secondary script. In the past I have accomplished this with an `kitchen verify || true` and then used the inspec json to pass/fail my run after I do more detailed analysis.

Would we be able to add a flag to allow for this.

**Comment by damacus** [comment] 2023-02-08 14:32
You'd probably want to add a separate step that always runs even if test-kitchen fails. 

I'm going to close this as, working as intended 👍🏼

**Closed as not planned by damacus** 2023-02-08 14:32 UTC
